### PR TITLE
Default to RelWithDebInfo configuration, and use that for our binaries too

### PR DESCRIPTION
**Pull request by bobsummerwill**

### CODE REVIEW

**Comment by gcolvin** [comment]
Bob says elsewhere, "I don't know if that happens early enough, whether it will work properly for Windows, etc, but it should flip that default config to Release."  I can't test on Windows, but on Ubuntu this fixes the problems I saw.  CMake claims it is configuring for release, and in fact puts -O3 and -DNDEBUG on the C++ command line.  I've added the 'bug' label because without this change customers (and even this developer) following our directions to 'cmake ..' would get a completely unoptimized build.

**Comment by gcolvin** [comment]
@chriseth says "I think we should go for RelWithDebugInfo by default and for the official binaries."

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/webthree-umbrella/issues/497.

**Comment by gcolvin** [comment]
Seems  ethereum/webthree-umbrella#497 has superseded this one, so closing again..

**Comment by bobsummerwill** [comment]
Yeah - but this is the PR, and it never got committed, so I'll reopen, and then flip the config to be defaulted to.

**Comment by bobsummerwill** [comment]
^ OK - updated.

**Comment by gcolvin** [comment]
Phew.  Thanks @bobsummerwill

**Pull request merged**
