### PR TITLE
Rework clang sanitizer support.

### PR DESCRIPTION
**Pull request by chfast**
cmake now accepts -DSANITIZE option with values matching clang's -fsanitize flag. E.g. add `-DSANITIZE=address` to enable address sanitizer.

### CODE REVIEW

**Comment by chfast** [comment]
I would label it with `gotissues` but that one is missing here.

**Comment by LefterisJP** [comment]
I will add the label.

Also could we somehow give one sanitizing argument to cmake and have it compile with address sanitizing if clang >= 3.1 and gcc >= 4.8? 

Because I think now we only enable it for Clang.

**Comment by chfast** [comment]
I will work on that. It needs to be "cached cmake option" first of all because if not I cannot query in in libevmjit (I think that's the reason).

So, you want support for GCC >= 4.8 too, right?

**Comment by LefterisJP** [comment]
Hmm I see. Yes that would be okay.

As for `gcc` support yes it won't be difficult. You only need to provide the same argument as `clang` needs and it will work if the gcc version supports it. 

I think it's `-fsanitize=address` both as a compile and as a linker flag.

**Pull request merged**
