### PR TITLE
Only looking for ssh2, openssl and lib when static linkage is enabled, to avoid spammy messages

### PR DESCRIPTION
**Pull request by bobsummerwill**
This change also lets us make those dependencies be REQUIRED, though we aren't 100% sure that these will be the exact right set for all platforms given that the curl binaries are always current prebuilt, and we don't control the build options.

CC @rainbeam.

### CODE REVIEW

**Comment by rainbreak** [comment]
That's sensible. However, I think optional was the right call initially. 

As far as I can tell, curl is only used in `libjson-rpc-cpp/src/jsonrpccpp/client/connectors/httpclient.cpp` with only the basic http functionality being used.

So I don't think curl needs to necessarily be built with the above dependencies. The only reason for specifying them is so that cmake correctly includes them when linking. Given that they may or may not be there at all, optional is the right flag.

**Comment by bobsummerwill** [comment]
Optional in that for the static-linkage case end-users would choose to have only a subset of them installed depending on how the curl binary they have is built?

The problem with that approach, though, is that it exposes end-users to random build breaks which they have to chase down the root causes of, only to find "Oh yeah, you need ssh2, but our build system doesn't enforce that because you might not need it on some platforms".

I think that given you don't control those binaries, it's better to be "greedy" and just require the union of them all.    It might pull in more than you need on some platforms, but the dead-code stripper can deal with that.     Better that that hurting end-users into having to waste their time working out what is wrong.

But the better solution here, which I hope we can get to soon enough, would be to have curl as a sub-module and built that from source too, so we can control the version and exactly how it is built, to have an absolute bare minimum version.

Because, as you point out, it is used in a very, very limited way by `eth`.

**Comment by bobsummerwill** [comment]
See https://github.com/cinemast/libjson-rpc-cpp/blob/master/src/jsonrpccpp/client/connectors/httpclient.cpp.

So I think our direct API dependencies are:
- curl_global_init() and curl_global_cleanup() - via a horrible static object pattern.
- curl_easy_init() and curl_easy_cleanup()
- curl_easy_setopt()
- curl_slist_append()
- curl_easy_setopt()
- curl_easy_perform()
- curl_slist_free_all()
- curl_easy_getinfo()
- curl_slist and CURLcode.

**Comment by rainbreak** [comment]
> Optional in that for the static-linkage case end-users would choose to have only a subset of them installed depending on how the curl binary they have is built?

Yes. SSL / SSH and libz are very common build options with curl, but they aren't strictly necessary.

It might be an intractable problem though. From a user perspective it is probably better to provide a minimal curl build, when doing static linking.

I'm experimenting with a stripped down curl build on debian now.

**Pull request merged**
