### PR TITLE
Stripping further JSON-RPC references for libethereum.

### PR DESCRIPTION
**Pull request by bobsummerwill**

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Hmm.   Automation results here look wrong:

Ubuntu failure looks like it is missing the code-change for this header-move:

http://52.28.164.97/job/project-build/label=master/3068/console

from /var/jenkins_home/sharedspace/webthree-helpers/label/master/libethereum/libevm/VM.cpp:23:
/var/jenkins_home/sharedspace/webthree-helpers/label/master/webthree-helpers/cmake/../../libethereum/libethereum/State.h:29:36: fatal error: libdevcrypto/OverlayDB.h: No such file or directory
 #include <libdevcrypto/OverlayDB.h>

**Comment by bobsummerwill** [comment]
Mac link errors are legitimate, though.
I'm going to need to make matching ADDITIONS of the JsonRpc linkage into the applications themselves now, to offset for their implicit linkage via libethereum which this change was cleaning up.

See http://52.28.164.97/job/project-build/label=macosx_slave/3068/console

Leave it with me!

**Comment by chriseth** [comment]
Windows too:

```
Creating library C:/Jenkins/sharedspace/webthree-helpers/label/windows-slave/alethzero/build/alethone/Release/AlethOne.lib and object C:/Jenkins/sharedspace/webthree-helpers/label/windows-slave/alethzero/build/alethone/Release/AlethOne.exp

    15>aleth.lib(Slave.obj) : error LNK2019: unresolved external symbol "public: __cdecl jsonrpc::HttpClient::HttpClient(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0HttpClient@jsonrpc@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: __cdecl std::_Ref_count_obj<class jsonrpc::HttpClient>::_Ref_count_obj<class jsonrpc::HttpClient><class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&)" (??$?0V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@?$_Ref_count_obj@VHttpClient@jsonrpc@@@std@@QEAA@$$QEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@1@@Z) [C:\Jenkins\sharedspace\webthree-helpers\label\windows-slave\alethzero\build\alethone\AlethOne.vcxproj]
    15>aleth.lib(Slave.obj) : error LNK2019: unresolved external symbol "public: __cdecl jsonrpc::Client::Client(class jsonrpc::IClientConnector &,enum jsonrpc::clientVersion_t)" (??0Client@jsonrpc@@QEAA@AEAVIClientConnector@1@W4clientVersion_t@1@@Z) referenced in function "public: __cdecl FarmClient::FarmClient(class jsonrpc::IClientConnector &,enum jsonrpc::clientVersion_t)" (??0FarmClient@@QEAA@AEAVIClientConnector@jsonrpc@@W4clientVersion_t@2@@Z) [C:\Jenkins\sharedspace\webthree-helpers\label\windows-slave\alethzero\build\alethone\AlethOne.vcxproj]
```

**Comment by chriseth** [comment]
If the problem with the missing headers persists, wipe the workspace for the project-build job on jenkins.
If you want to re-trigger jenkins, force-push an amended commit (which changes nothing apart from the timestamp) to your branch.

**Comment by bobsummerwill** [comment]
Yes, and that makes complete sense.    It will be present on Ubuntu as well, only hiding behind that bogus reported break.

Just looking at https://github.com/ethereum/webthree-umbrella/wiki/Continuous-Integration, it appears that the extra metadata thing is hard-coded to look at a user account, so I am going to need to make a fork of the alethzero repo into bobsummerwill, right?   There is no way for me to specify to get the branch for the other half of this change from a doublethinkco repo.     Please could you confirm?

**Comment by bobsummerwill** [comment]
OK - All fixed.     Had to do some force-pushes to webthree-helper to trigger this to run again.    Had to do a "clean workspace" to resolve the Ubuntu issue.

No passing.    So it was just a one-liner in alethzero and in libaleth, to re-add the JsonRpc dependencies to only those modules.

https://github.com/ethereum/alethzero/pull/130

**Pull request merged**
