### PR TITLE
Copying the last two scripts from Jenkins "managed scripts".

### PR DESCRIPTION
**Pull request by bobsummerwill**
1. Powershell script used to create the Windows ZIP.
2. Python script for moving issues from cpp-ethereum to webthree-umbrella (which we might use to move them back).

### CODE REVIEW

**Comment by bobsummerwill** [comment]
PS.    I also changed the wildcard in the Powershell script from \* to msvc*120.dll.

That should constrain the runtime libraries so that we only get the C (msvcr120.dll) and C++ (msvcp120.dll) runtime libraries, not the unnecessary WinRT library which we currently have too (vccorlib120.dll).

**Comment by chriseth** [comment]
Are you sure that we actually only need the msvc*120.dll? I would actually prefer including more than including less.

**Comment by chriseth** [comment]
How do you run the powershell script? If we do not run it form github, I would prefer leaving it only in the jenkins config to avoid change conflicts.

**Comment by bobsummerwill** [comment]
Hmm.   You might have a point there about running Powershell from Jenkins, @chriseth.
I guess that we have a simple short-cut for Bash scripts, because we don't need a "Jenkins plugin" for running those, do we?    But yeah, doing a curl and run on Windows might not be so simple.      I will think some more on that.

In the meantime, I have updated the managed Powershell script within Jenkins itself to match my wildcard update, and am manually running a develop ethbinaries, to check that works.    The expression  will just remove the single WinRT binary, which I am very confident is not required.    That is for https://en.wikipedia.org/wiki/Windows_Runtime, which we aren't using.

On the assumption that the new ZIP from Jenkins is OK, I will then look for a means to run the Powershell script from webthree-helpers, and if I can find a means then I will merge this as-is.    If not, I will drop the Powershell from this PR.

**Comment by chfast** [comment]
The Powershell script is used only by single Jenkins project. I think it goes like that:
1. Pack VS runtime dlls (using Powershell because Jenkins/Archive cannot access files outside of the workspace).
2. Pack build artifacts, including archive from 1 (using Jenkins/Archive).

How about changing that to:
1. Copy VS runtime dlls (using bash or Windows shell).
2. Pack build artifacts, including files from 1 (using Jenkins/Archive).

**Comment by bobsummerwill** [comment]
@chfast Hey - looking into this one again, I think what actually is happening on Windows is the following:
1. ethbinaries.sh executed (within Cygwin, I assume?), which will call `make install` which will call the CPack/NSIS target which creates the `webthree-umbrella\build\_CPack_Packages\win64\NSIS\Ethereum\eth` directory.   I'm guessing this is an interim step for the installer which just happens to have the content which is wanted in the ZIP?
2. Powershell called, which copies the VC++ runtime DLLs from Program Files into this temp directory (which will be the "cheat" step which needs PowerShell)
3. And then the last line of the PowerShell ZIPs that up.

**Comment by bobsummerwill** [comment]
Hey @chfast, @chriseth!
Do you think my analysis above is correct?

**Comment by chfast** [comment]
I'm not sure it is correct. Does NSIS depends on `make install`?

For me the most interesting question is why/if do you need to use PowerShell to make an archive. Jenkins knows how to make an archive.

**Comment by chriseth** [comment]
So, can this be converted from powershell to something else or even to something that does not need a script?

**Comment by bobsummerwill** [comment]
None of this matters anymore.   Appveyor implementation will be way simpler.

**Pull request closed without merging**
